### PR TITLE
Update version to 11.5.150.18

### PR DESCRIPTION
**Pull request by MeirShpilraien**

### CODE REVIEW

**Comment by MeirShpilraien** [comment]
I already consulted @chayim how we can do that. @chayim can you advice again?
Till then I do not think it should prevent us merging this...

**Comment by MeirShpilraien** [comment]
> We have already closed our eyes on that like ten or more times. How many more there are going to be before we finally address this?

You are welcome to come up with a suggestion and open a PR...

**Comment by chayim** [comment]
@MeirShpilraien see what I just pushed. Let's see if it passes.

**Comment by MeirShpilraien** [comment]
@chayim lets do it on another PR, its gone take 6 hours and I do not see why holding the version for this ... also I remember trying this and it did not work (but I could be missing something)...

**Comment by MeirShpilraien** [comment]
You can see that it is not working:
https://github.com/RedisGears/v8-build/actions/runs/5596563008

**Pull request merged**
